name: CI/CD

on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      # v4.1.1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          submodules: 'true'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
          check-latest: true
          cache: true      

      - uses: securego/gosec@master

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: go test
        run: make test
        shell: bash
