name: CI/CD

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # v4.1.1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          submodules: 'true'

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: './backend/go.mod'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ./backend

  test:
    runs-on: ubuntu-latest
    
    steps:
      # v4.1.1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          submodules: 'true'

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: './backend/go.mod'
          
      - name: Check Security Vulnerabilities
        uses: securego/gosec@master
        
      - name: Linting
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ./backend

      - name: Run Tests
        run: make test
        shell: bash
      
      - name: Run Build
        run: make build
        shell: bash
